[package]
name = "little-a-map"
version = "0.8.0"
repository = "https://github.com/AndrewKvalheim/little-a-map"
categories = ["command-line-utilities"]
keywords = ["minecraft"]
description = "Players can have little a map—if they've surveyed the area in-game. This tool renders a composite of existing map items with the goal of minimizing external effects on survival gameplay."
authors = ["Andrew Kvalheim <Andrew@Kvalhe.im>"]
license = "GPL-3.0-or-later"
readme = "README.md"
edition = "2018"

[workspace]
members = ["lib"]

[[bin]]
name = "little-a-map"
path = "src/main.rs"
bench = false

[dependencies]
anyhow = "1.0"
lib = { path = "./lib" }
paw = "1.0"
structopt = { version = "0.3", features = ["paw"] }

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "default"
harness = false
