[package]
name = "little-a-map"
version = "0.4.0"
repository = "https://github.com/AndrewKvalheim/little-a-map"
categories = ["command-line-utilities"]
keywords = ["minecraft"]
description = "Players can have little a map—if they've surveyed the area in-game. This tool renders a composite of existing map items with the goal of minimizing external effects on survival gameplay."
authors = ["Andrew Kvalheim <Andrew@Kvalhe.im>"]
license = "GPL-3.0-or-later"
readme = "README.md"
edition = "2018"

[dependencies]
askama = "0.10.2"
derivative = "2.1.1"
fastnbt = "0.6.0"
filetime = "0.2.10"
flate2 = "1.0.16"
glob = "0.3.0"
lazy_static = "1.4.0"
paw = "1.0"
png = "0.16.7"
rayon = "1.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
structopt = { version = "0.3", features = ["paw"] }
